### ISSUE TITLE
Possible mistake in noise placeholders 

### ISSUE THREAD

**Issue by ghost** [AndyHsiao26/InfoGAN-tensorflow#1]
Why do you have three noise placeholders for your network? 

I understand that one noise vector is needed for `z` and the other noise vector for the code `c` Since the generator is G(z,c). However what is the third noise vector for?
```
with tf.name_scope('noise_sample'):
            self.z_cat = tf.placeholder(tf.int32, [None])
            self.z_cont = tf.placeholder(tf.float32, [None, args.num_cont])
            self.z_rand = tf.placeholder(tf.float32, [None, args.num_rand])
```

**Comment by fangihsiao** [comment]
Hello @ImranRolo, 

In the paper, the authors use a 74-dimensional noise vector composed of one ten-dimensional categorical code, 2 continuous latent codes and 62 noise variables `z`.

The first two placeholders are categorical and continuous codes and the third one is the noise variables.
